# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 845fb4c2935725c71aef018aefb003f9575e0437e45d1d3e8f64d2eff685240307afff38ce8fd6252fe15f5600ac2d250b8d9c2c825cb57f3febf39ac8603525

test:
  secret_key_base: 00bb773706f66188a042b2d93e944cc6fb4b618309516153fdac0664235caff3360dc6261d0e02adfec8c609248ccebad64f206a14a1dce2dfbe4f2a352830a0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
